// 이 파일은 애플리케이션의 주요 설정을 정의합니다.
// API 기본 URL, 초기 마커 색상, 정적 데이터 목록 (예: 수능 탐구 과목) 등을 포함합니다.
// 이 값을 변경하면 애플리케이션 전체 동작에 영향을 줄 수 있습니다.

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://dotorimuuk.duckdns.org/api'; // 백엔드 API의 기본 URL
export const INITIAL_MARKER_COLOR = '#cccccc'; // 필터 적용 전 초기 마커 색상 (회색)
export const INITIAL_MARKER_CLICK_MESSAGE = "학과와 성적을 입력하고 필터를 적용하여 상세 정보를 확인하세요."; // 초기 마커 클릭 시 표시될 메시지

// 수능 탐구 과목 목록 (정적 데이터) - ApiSubjectInfo 타입과 일치
// API에서 동적으로 가져오기 전 또는 실패 시 사용될 수 있습니다.
// 이 목록은 이제 '과목' 목록 중 탐구 영역에 해당합니다. '교과' 목록은 별도로 API에서 가져옵니다.
export const SUNEUNG_EXPLORER_SUBJECTS_STATIC: {subjectCode: string, subjectName: string}[] = [
    { subjectCode: "SA01", subjectName: "생활과 윤리" },
    { subjectCode: "SA02", subjectName: "윤리와 사상" },
    { subjectCode: "SA03", subjectName: "한국지리" },
    { subjectCode: "SA04", subjectName: "세계지리" },
    { subjectCode: "SA05", subjectName: "동아시아사" },
    { subjectCode: "SA06", subjectName: "세계사" },
    { subjectCode: "SA07", subjectName: "경제" },
    { subjectCode: "SA08", subjectName: "정치와 법" },
    { subjectCode: "SA09", subjectName: "사회·문화" },
    { subjectCode: "SC01", subjectName: "물리학Ⅰ" },
    { subjectCode: "SC02", subjectName: "화학Ⅰ" },
    { subjectCode: "SC03", subjectName: "생명과학Ⅰ" },
    { subjectCode: "SC04", subjectName: "지구과학Ⅰ" },
    { subjectCode: "SC05", subjectName: "물리학Ⅱ" },
    { subjectCode: "SC06", subjectName: "화학Ⅱ" },
    { subjectCode: "SC07", subjectName: "생명과학Ⅱ" },
    { subjectCode: "SC08", subjectName: "지구과학Ⅱ" },
];

// 수능 국어 선택과목 옵션 (정적 데이터)
export const SUNEUNG_KOREAN_OPTIONS_STATIC: {subjectCode: string, subjectName: string}[] = [
    { subjectCode: "KOR_OPT_HWAPJAK", subjectName: "화법과 작문"},
    { subjectCode: "KOR_OPT_EONMAE", subjectName: "언어와 매체"},
];

// 수능 수학 선택과목 옵션 (정적 데이터)
export const SUNEUNG_MATH_OPTIONS_STATIC: {subjectCode: string, subjectName: string}[] = [
    { subjectCode: "MAT_OPT_HWAKTONG", subjectName: "확률과 통계"},
    { subjectCode: "MAT_OPT_MIJEOK", subjectName: "미적분"},
    { subjectCode: "MAT_OPT_GIHA", subjectName: "기하"},
];

// 내신 성취도 레벨 목록 (정적 데이터)
export const NAESIN_ACHIEVEMENT_LEVELS_STATIC: string[] = ['A', 'B', 'C', 'D', 'E', 'P', 'F', 'I', 'PASS', 'FAIL'];

// 학과 계열 분류 데이터
export interface DepartmentCategory {
    majorCode: string;
    majorName: string;
    mediumCode: string;
    mediumName: string;
    minorCode: string;
    minorName: string;
}

export const DEPARTMENT_CATEGORIES: DepartmentCategory[] = [
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "001", minorName: "언어학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "002", minorName: "국어ㆍ국문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "003", minorName: "독일어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "004", minorName: "러시아어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "005", minorName: "스페인어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "006", minorName: "영어ㆍ영문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "007", minorName: "일본어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "008", minorName: "중국어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "009", minorName: "프랑스어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "010", minorName: "기타아시아어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "011", minorName: "기타유럽어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "012", minorName: "교양어ㆍ문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "148", minorName: "문예창작학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "01", mediumName: "언어ㆍ문학", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "02", mediumName: "인문학", minorCode: "013", minorName: "철학ㆍ윤리학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "02", mediumName: "인문학", minorCode: "014", minorName: "역사ㆍ고고학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "02", mediumName: "인문학", minorCode: "015", minorName: "종교학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "02", mediumName: "인문학", minorCode: "016", minorName: "문화ㆍ민속ㆍ미술사학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "02", mediumName: "인문학", minorCode: "017", minorName: "국제지역학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "02", mediumName: "인문학", minorCode: "018", minorName: "교양인문학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "02", mediumName: "인문학", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "033", minorName: "경영학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "034", minorName: "경제학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "035", minorName: "경영정보학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "037", minorName: "무역ㆍ유통학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "038", minorName: "광고ㆍ홍보학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "039", minorName: "관광학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "040", minorName: "부동산" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "151", minorName: "금융ㆍ보험학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "152", minorName: "회계ㆍ세무학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "03", mediumName: "경영ㆍ경제", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "04", mediumName: "법학", minorCode: "019", minorName: "법학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "04", mediumName: "법학", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "020", minorName: "심리학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "021", minorName: "사회학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "022", minorName: "정치외교학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "023", minorName: "국제학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "024", minorName: "아동ㆍ가족학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "025", minorName: "사회복지학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "026", minorName: "소비자ㆍ가정자원" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "027", minorName: "언론ㆍ방송ㆍ매체학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "028", minorName: "도시ㆍ지역ㆍ지리학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "029", minorName: "행정학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "030", minorName: "인류학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "031", minorName: "문헌정보학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "032", minorName: "교양사회과학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "149", minorName: "군사ㆍ국방ㆍ안보" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "05", mediumName: "사회과학", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "98", mediumName: "교육", minorCode: "042", minorName: "교육학" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "98", mediumName: "교육", minorCode: "043", minorName: "중등언어교육" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "98", mediumName: "교육", minorCode: "046", minorName: "초등교육" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "98", mediumName: "교육", minorCode: "153", minorName: "중등사회과교육" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "98", mediumName: "교육", minorCode: "154", minorName: "유아교육" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "98", mediumName: "교육", minorCode: "155", minorName: "특수교육" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "98", mediumName: "교육", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "99", mediumName: "N.C.E", minorCode: "041", minorName: "비서" },
    { majorCode: "A", majorName: "인문ㆍ사회", mediumCode: "99", mediumName: "N.C.E", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "06", mediumName: "농림ㆍ수산", minorCode: "058", minorName: "작물ㆍ원예학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "06", mediumName: "농림ㆍ수산", minorCode: "059", minorName: "산림학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "06", mediumName: "농림ㆍ수산", minorCode: "060", minorName: "축산학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "06", mediumName: "농림ㆍ수산", minorCode: "061", minorName: "수산학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "06", mediumName: "농림ㆍ수산", minorCode: "062", minorName: "농림수산환경생태학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "06", mediumName: "농림ㆍ수산", minorCode: "063", minorName: "농림수산바이오시스템공학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "06", mediumName: "농림ㆍ수산", minorCode: "064", minorName: "식품가공학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "06", mediumName: "농림ㆍ수산", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "07", mediumName: "화학ㆍ생명과학ㆍ환경", minorCode: "055", minorName: "화학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "07", mediumName: "화학ㆍ생명과학ㆍ환경", minorCode: "056", minorName: "생명과학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "07", mediumName: "화학ㆍ생명과학ㆍ환경", minorCode: "057", minorName: "환경학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "07", mediumName: "화학ㆍ생명과학ㆍ환경", minorCode: "156", minorName: "바이오테크놀로지학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "07", mediumName: "화학ㆍ생명과학ㆍ환경", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "08", mediumName: "생활과학", minorCode: "066", minorName: "식품영양학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "08", mediumName: "생활과학", minorCode: "067", minorName: "조리과학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "08", mediumName: "생활과학", minorCode: "068", minorName: "의류ㆍ의상학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "08", mediumName: "생활과학", minorCode: "069", minorName: "주거학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "08", mediumName: "생활과학", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "09", mediumName: "수학ㆍ물리ㆍ천문ㆍ지구", minorCode: "048", minorName: "수학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "09", mediumName: "수학ㆍ물리ㆍ천문ㆍ지구", minorCode: "049", minorName: "통계학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "09", mediumName: "수학ㆍ물리ㆍ천문ㆍ지구", minorCode: "050", minorName: "물리학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "09", mediumName: "수학ㆍ물리ㆍ천문ㆍ지구", minorCode: "051", minorName: "천문ㆍ기상학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "09", mediumName: "수학ㆍ물리ㆍ천문ㆍ지구", minorCode: "052", minorName: "지구과학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "09", mediumName: "수학ㆍ물리ㆍ천문ㆍ지구", minorCode: "053", minorName: "해양학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "09", mediumName: "수학ㆍ물리ㆍ천문ㆍ지구", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "21", mediumName: "간호", minorCode: "112", minorName: "간호학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "22", mediumName: "보건", minorCode: "113", minorName: "보건학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "22", mediumName: "보건", minorCode: "114", minorName: "재활치료" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "22", mediumName: "보건", minorCode: "115", minorName: "임상보건" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "22", mediumName: "보건", minorCode: "116", minorName: "보건관리" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "22", mediumName: "보건", minorCode: "118", minorName: "피부미용" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "22", mediumName: "보건", minorCode: "163", minorName: "동물보건" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "22", mediumName: "보건", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "23", mediumName: "약학", minorCode: "110", minorName: "약학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "23", mediumName: "약학", minorCode: "111", minorName: "한약학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "23", mediumName: "약학", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "25", mediumName: "의료예과", minorCode: "144", minorName: "의예과" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "25", mediumName: "의료예과", minorCode: "145", minorName: "치의예과" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "25", mediumName: "의료예과", minorCode: "146", minorName: "한의예과" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "25", mediumName: "의료예과", minorCode: "147", minorName: "수의예과" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "98", mediumName: "교육", minorCode: "070", minorName: "중등자연과학교육" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "98", mediumName: "교육", minorCode: "117", minorName: "간호ㆍ보건 교육" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "98", mediumName: "교육", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "99", mediumName: "N.C.E", minorCode: "071", minorName: "교양자연과학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "99", mediumName: "N.C.E", minorCode: "150", minorName: "의과학" },
    { majorCode: "B", majorName: "자연과학", mediumCode: "99", mediumName: "N.C.E", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "10", mediumName: "무용ㆍ체육", minorCode: "119", minorName: "무용" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "10", mediumName: "무용ㆍ체육", minorCode: "120", minorName: "체육" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "10", mediumName: "무용ㆍ체육", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "11", mediumName: "연극ㆍ영화", minorCode: "121", minorName: "연극" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "11", mediumName: "연극ㆍ영화", minorCode: "122", minorName: "영화" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "11", mediumName: "연극ㆍ영화", minorCode: "123", minorName: "방송연예" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "11", mediumName: "연극ㆍ영화", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "12", mediumName: "응용예술", minorCode: "135", minorName: "사진" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "12", mediumName: "응용예술", minorCode: "136", minorName: "만화" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "12", mediumName: "응용예술", minorCode: "137", minorName: "애니메이션" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "12", mediumName: "응용예술", minorCode: "138", minorName: "게임" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "12", mediumName: "응용예술", minorCode: "139", minorName: "영상예술" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "12", mediumName: "응용예술", minorCode: "140", minorName: "음향" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "12", mediumName: "응용예술", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "13", mediumName: "미술", minorCode: "124", minorName: "공예" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "13", mediumName: "미술", minorCode: "125", minorName: "디자인" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "13", mediumName: "미술", minorCode: "126", minorName: "순수미술" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "13", mediumName: "미술", minorCode: "127", minorName: "응용미술" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "13", mediumName: "미술", minorCode: "128", minorName: "미술학" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "13", mediumName: "미술", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "14", mediumName: "음악", minorCode: "129", minorName: "작곡" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "14", mediumName: "음악", minorCode: "130", minorName: "성악" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "14", mediumName: "음악", minorCode: "131", minorName: "기악" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "14", mediumName: "음악", minorCode: "132", minorName: "국악" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "14", mediumName: "음악", minorCode: "133", minorName: "실용음악" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "14", mediumName: "음악", minorCode: "134", minorName: "음악학" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "14", mediumName: "음악", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "98", mediumName: "교육", minorCode: "141", minorName: "중등예술ㆍ체육교육" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "98", mediumName: "교육", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "99", mediumName: "N.C.E", minorCode: "142", minorName: "뷰티아트" },
    { majorCode: "C", majorName: "예ㆍ체능", mediumCode: "99", mediumName: "N.C.E", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "084", minorName: "전기공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "085", minorName: "전자공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "086", minorName: "제어계측공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "087", minorName: "광학공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "088", minorName: "의공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "089", minorName: "응용소프트웨어공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "090", minorName: "전산학ㆍ컴퓨터공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "091", minorName: "정보ㆍ통신공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "157", minorName: "인공지능공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "15", mediumName: "전기ㆍ전자ㆍ컴퓨터", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "16", mediumName: "건설", minorCode: "072", minorName: "건축학" },
    { majorCode: "D", majorName: "공학", mediumCode: "16", mediumName: "건설", minorCode: "073", minorName: "건축공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "16", mediumName: "건설", minorCode: "074", minorName: "조경학" },
    { majorCode: "D", majorName: "공학", mediumCode: "16", mediumName: "건설", minorCode: "075", minorName: "토목공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "16", mediumName: "건설", minorCode: "076", minorName: "도시공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "16", mediumName: "건설", minorCode: "077", minorName: "환경공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "16", mediumName: "건설", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "17", mediumName: "산업ㆍ안전", minorCode: "102", minorName: "산업공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "17", mediumName: "산업ㆍ안전", minorCode: "103", minorName: "안전공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "17", mediumName: "산업ㆍ안전", minorCode: "104", minorName: "방재공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "17", mediumName: "산업ㆍ안전", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "18", mediumName: "재료", minorCode: "092", minorName: "금속공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "18", mediumName: "재료", minorCode: "093", minorName: "반도체공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "18", mediumName: "재료", minorCode: "094", minorName: "신소재공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "18", mediumName: "재료", minorCode: "095", minorName: "세라믹공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "18", mediumName: "재료", minorCode: "096", minorName: "재료공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "18", mediumName: "재료", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "19", mediumName: "기계", minorCode: "078", minorName: "기계공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "19", mediumName: "기계", minorCode: "079", minorName: "기전공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "19", mediumName: "기계", minorCode: "080", minorName: "조선ㆍ해양공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "19", mediumName: "기계", minorCode: "081", minorName: "항공ㆍ우주공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "19", mediumName: "기계", minorCode: "082", minorName: "철도공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "19", mediumName: "기계", minorCode: "083", minorName: "자동차공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "19", mediumName: "기계", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "20", mediumName: "화공ㆍ고분자ㆍ에너지", minorCode: "097", minorName: "화학공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "20", mediumName: "화공ㆍ고분자ㆍ에너지", minorCode: "098", minorName: "에너지공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "20", mediumName: "화공ㆍ고분자ㆍ에너지", minorCode: "099", minorName: "고분자공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "20", mediumName: "화공ㆍ고분자ㆍ에너지", minorCode: "100", minorName: "생명공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "20", mediumName: "화공ㆍ고분자ㆍ에너지", minorCode: "101", minorName: "섬유공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "20", mediumName: "화공ㆍ고분자ㆍ에너지", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "26", mediumName: "교통・수송", minorCode: "158", minorName: "교통시스템공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "26", mediumName: "교통・수송", minorCode: "159", minorName: "철도운전제어학" },
    { majorCode: "D", majorName: "공학", mediumCode: "26", mediumName: "교통・수송", minorCode: "160", minorName: "선박운항학" },
    { majorCode: "D", majorName: "공학", mediumCode: "26", mediumName: "교통・수송", minorCode: "161", minorName: "항공운항학" },
    { majorCode: "D", majorName: "공학", mediumCode: "26", mediumName: "교통・수송", minorCode: "162", minorName: "무인항공기(운항)학" },
    { majorCode: "D", majorName: "공학", mediumCode: "26", mediumName: "교통・수송", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "98", mediumName: "교육", minorCode: "105", minorName: "중등공학교육" },
    { majorCode: "D", majorName: "공학", mediumCode: "98", mediumName: "교육", minorCode: "106", minorName: "교양공학" },
    { majorCode: "D", majorName: "공학", mediumCode: "98", mediumName: "교육", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "D", majorName: "공학", mediumCode: "99", mediumName: "N.C.E", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "E", majorName: "의학", mediumCode: "24", mediumName: "의료", minorCode: "065", minorName: "수의학" },
    { majorCode: "E", majorName: "의학", mediumCode: "24", mediumName: "의료", minorCode: "107", minorName: "의학" },
    { majorCode: "E", majorName: "의학", mediumCode: "24", mediumName: "의료", minorCode: "108", minorName: "치의학" },
    { majorCode: "E", majorName: "의학", mediumCode: "24", mediumName: "의료", minorCode: "109", minorName: "한의학" },
    { majorCode: "E", majorName: "의학", mediumCode: "24", mediumName: "의료", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "E", majorName: "의학", mediumCode: "99", mediumName: "N.C.E", minorCode: "999", minorName: "N.C.E" },
    { majorCode: "F", majorName: "광역", mediumCode: "99", mediumName: "N.C.E", minorCode: "999", minorName: "N.C.E" }
];